### ISSUE TITLE
Syntaxes added after `just` 1.36.0

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#115]
Tracking the list of syntaxes to add support for after the next `just` release is tagged:

- [x] [`&&` and `||` operators](https://github.com/casey/just/commit/7030e9cac6f1a13bd4d366fab66f0341edeb3002)
- [x] [Terminal escape sequence constants](https://github.com/casey/just/commit/bbc087294781ee36d2b7c0fbb64d70ac2959558f)
- [x] [`style()`](https://github.com/casey/just/commit/084a2d2de3b80e7a4c62181ff1a25642ac075223)
