### ISSUE TITLE
Syntaxes added after `just` 1.38.0

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#117]
Tracking the list of syntaxes to add support for after the next `just` release is tagged:

- [x] `read()` [1](https://github.com/casey/just/commit/464fdbc1bb07b4bd0f70dd6dfe7d454befd8b81c), [2](https://github.com/casey/just/commit/8b35450c55f1b75321f5c2d7cd7f5c20806f63a7)
- [x] [Regex mismatch conditional `!~`](https://github.com/casey/just/commit/53f8619e36b6e9460ca3e6bf178c9cb2fe724686)
- [x] [`set no-exit-message` and `[exit-message]`](https://github.com/casey/just/commit/ab3da9bf64661079b75ec310fc17d61c540e569d)
- [x] [`which()` and `require()`](https://github.com/casey/just/commit/398eb29f06e6b5c514fcf54fb0c20e9df29f3838)
