### ISSUE TITLE
Syntaxes added after `just` 1.14.0

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#44]
Tracking the list of syntaxes to add support for after the next `just` release is tagged:

- [x] [`env()`](https://github.com/casey/just/commit/bba673fd791fa08aac95cf263141a4c69162681b)
- [x] [Escaped newlines in recipe declarations and elsewhere](https://github.com/casey/just/commit/30bcf28fdec43dec96b014ac79a49b6c57f3f10e)
- [x] [`num_cpus()`](https://github.com/casey/just/pull/1568)
