### ISSUE TITLE
Syntaxes added after `just` 1.22.1

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#70]
Tracking the list of syntaxes to add support for after the next `just` release is tagged:

- [x] [Standard directories functions](https://github.com/casey/just/commit/c2af5a1dd6f471349b71a63703ed51e722fba7a2)
- [x] [`just_pid()`](https://github.com/casey/just/commit/53cea2f82351012f9c6708dd109ad2922ea0487c)
- [x] [`set quiet` and `[no-quiet]`](https://github.com/casey/just/commit/5bbc89b7189caa2354577129f6a97b7407cf1e26)
- [x] [Custom prompt for `confirm`](https://github.com/casey/just/commit/8bd411de45fa12df91a4c174f3ff68e2497b6615)
