### ISSUE TITLE
Expand contributor documentation

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#75]
Reviewing https://github.com/NoahTheDuke/vim-just/pull/73 brought to my attention that `vim-just` lacks sufficient documentation for contributors.  Some things contributors may need to understand about our code are entirely undocumented.

`vim-just` at this point has too much intricacy to reasonably cram all the missing contributor documentation in README.md, so addressing this involves multiple parts:

- [x] Move existing contributor documentation to a `CONTRIBUTING.md`.  And change the "Contributing & Development" section of README.md to be one or two short sentences simply linking to CONTRIBUTING.md.
- [x] Add some contributing guidelines.  Because it has happened more than once that someone makes a PR with no description, to fix something for which no issue was filed here, which leads to additional avoidable back-and-forth.  Might be an idea to require that PRs state the rationale upfront (which in case of feature additions, could simply be a link to `just` documentation or `just` repo where the feature is documented/implemented).
- [x] Put [more detailed explanation of how syntax tests work](https://github.com/NoahTheDuke/vim-just/issues/21#issuecomment-1474302076) in contributor documentation
- [x] Document which syntax highlighting test cases are intended to be working, runnable justfiles (as opposed to only demonstrating syntaxes regardless of whether `just` would accept the whole) [Done: documented which are _not_ runnable and added a check recipe to tests justfile for the rest]
- [x] Document the ftdetect test cases file format.  It would be best to do this in comments in the ftdetect cases file itself, but JSON is not comment-friendly.  So we will need to convert it to a different format.  I think the best option would be YAML: it supports comments, its syntax seems more straightforward than JSON for this, and the `serde_yaml` crate is maintained by one of the `serde` devs.  Had a go at this and almost got it ready to push, but my dev environment borked badly before I could quite finalize it and I lost part of the changes :frowning_face: 
- [x] Add some explanatory comments to `syntax/just.vim`
- [x] ~~Include the text of https://github.com/casey/just/blob/e92ee922de9f862c1a2dd4654ea451bb6d1ad156/CONTRIBUTING.md while we're at it~~ Was decided to use a slightly modified version of that text.

Anything else to consider?
