### ISSUE TITLE
Syntaxes added after `just` 1.26.0

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#88]
Tracking the list of syntaxes to add support for after the next `just` release is tagged:

- [x] [`set allow-duplicate-variables`](https://github.com/casey/just/commit/e11684008e758424d9fbef2eae35c1c0be4962d7)
- [x] [`assert`](https://github.com/casey/just/commit/9aea3e679bcf44ab9e4e81066923ddb91b6ee98e)
- [x] [`prepend()`](https://github.com/casey/just/commit/89ccf42ddfd4ad443e68a9c42b5e0ddc68d1a038) and [`append()`](https://github.com/casey/just/commit/eb605181c2898b4cfa576360f4e1d43110679c57)
- [x] [Predefined constants](https://github.com/casey/just/commit/6907847a77de291fe8855e2a58a0bcb475e58dd0)
- [x] [`choose()`](https://github.com/casey/just/commit/7fa6ed8149a4b0554cbd712736eaa8d6ce3f1d66)
- [x] [`encode_uri_component()`](https://github.com/casey/just/commit/4961f49c381aa23ba226ff39a631487f7b0d0283)
- [x] [Shell-expanded strings](https://github.com/casey/just/commit/b1c7491486e2a563d349c429e7ebd3906ffd4b28)
- [x] [`shell()`](https://github.com/casey/just/commit/c6612de7601d16cdd4f88d0fd502f4a978518562)
- [x] [`[group('NAME')]` attribute](https://github.com/casey/just/commit/ed0dc20318ab4b8e31b8d4fb95361d880da105b7)
- [x] [`source_file()` and `source_directory()`](https://github.com/casey/just/commit/7fb04761b789267dedde8416b7c8fcbf8eed22e6)
- [x] [`[doc]` attribute](https://github.com/casey/just/commit/dcbd07f9d04df3c4106f625e4b7e6989d2c3ecb2)
