### ISSUE TITLE
Syntaxes added after `just` 1.28.0

### ISSUE THREAD

**Issue by laniakea64** [NoahTheDuke/vim-just#94]
Tracking the list of syntaxes to add support for after the next `just` release is tagged:

- [x] [`unexport`](https://github.com/casey/just/commit/38873dcb74dd69851e8ea5318d913260c0dc353c)
- [x] [`[attribute: value]` shorthand](https://github.com/casey/just/commit/1ca53e8b223edb0a1c6a66ec0cf1f0c2a6eab621)
- [x] [`is_dependency()`](https://github.com/casey/just/commit/5ac98c020df2cea79a1f41e6b22ad9a24d41cf90)
- [x] [`[positional-arguments]` attribute](https://github.com/casey/just/commit/1ce7a05befa8e2c0e3b05f52934087f57a439220)

**Comment by NoahTheDuke** [comment]
Nice catch!
